<?php
/*
 * ----------------------------------------------------------------------
 * AbstractConfigurationTest.php
 * ----------------------------------------------------------------------
 * CollectiveAccess
 * Open-source collections management software
 * ----------------------------------------------------------------------
 *
 * Software by Whirl-i-Gig (http://www.whirl-i-gig.com)
 * Copyright 2015-2020 Whirl-i-Gig
 *
 * For more information visit http://www.CollectiveAccess.org
 *
 * This program is free software; you may redistribute it and/or modify it under
 * the terms of the provided license as published by Whirl-i-Gig
 *
 * CollectiveAccess is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTIES whatsoever, including any implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This source code is free and modifiable under the terms of
 * GNU General Public License. (http://www.gnu.org/copyleft/gpl.html). See
 * the "license.txt" file for details, or visit the CollectiveAccess web site at
 * http://www.CollectiveAccess.org
 *
 * @package CollectiveAccess
 * @subpackage providence
 * @license http://www.gnu.org/copyleft/gpl.html GNU Public License version 3
 *
 * ----------------------------------------------------------------------
 *
 */

namespace Configuration;

use PHPUnit\Framework\TestCase;

require_once(__CA_BASE_DIR__ . '/ConfigurationSetup.php');


class AbstractConfigurationTest extends TestCase {

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->o_setup = new \CaSetup(__CA_BASE_DIR__ . '/tests/test-setup.yaml', null, array('allow_modifications'=>true));
    }

    public function testSet() {
        $o_setup = $this->o_setup;

        $o_setup->config_format= 'yaml';
        $this->assertEquals('yaml', $o_setup->get('config_format'));
    }

    public function testGetDotNotationExists() {
        $o_setup = $this->o_setup;

        $result = $o_setup->get('global.config_format');
        $this->assertEquals('yaml', $result);
    }

    public function testGetArrayExists() {
        $o_setup = $this->o_setup;

        $result = $o_setup->get(array('global', 'config_format'));
        $this->assertEquals('yaml', $result);
    }

    public function testGetDotNotationDoesNotExist() {
        $o_setup = $this->o_setup;

        $result = $o_setup->get('global.non_exists');
        $this->assertNull($result);
    }

    public function testGetKeyDoesNotExist() {
        $o_setup = $this->o_setup;

        $result = $o_setup->get('non_exists');
        $this->assertNull($result);
    }
}
