language: php
os: linux
dist: bionic

addons:
  apt:
    packages:
      - mysql-server-5.7
      - mysql-client-core-5.7
      - mysql-client-5.7

jobs:
  exclude:
  - php: 7.3
  - php: 7.4

git:
  depth: 5

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  - directories:
      # Cache vendor folder will speed up environment setup
      - vendor
      - tests/mysql_profile

services:
  - mysql

env:
# Here we list the profiles that we want to test, each one will be tested, per version of PHP, in parallel
#- PROFILE=default

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  # Remove xdebug to increase speed
  - phpenv config-rm xdebug.ini
  # Set up database
  - tests/database_setup.sh

install:
  # install all of the dependencies you need here
  # Create setup.php
  - export PROFILE=${PROFILE:-testing}
  - ln -s .travis.setup.php setup.php
  - if test -e vendor/composer.lock ; then echo "Restoring previous composer lock file"; cp vendor/composer.lock composer.lock; fi
  - composer install --prefer-dist
  - cp composer.lock vendor
  # Install the testing profile
  - tests/profile_setup.sh "$PROFILE"
  - composer show -i

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests
  # Set travisci configuration
  - ln -s .travis.setup.php setup.php
  # Create database
  - tests/database_setup.sh "$PROFILE"

script:
  # execute all of the commands which
  # should make the build pass or fail
  # Go into the tests directory to run the tests
  - cd tests/
  - ../vendor/bin/phpunit

branches:
  only:
    - develop
    - master
    - wip/playground
