language: php
sudo: required
os: linux
dist: bionic

addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7
    
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

env:
  # Here we list the profiles that we want to test, each one will be tested, per version of PHP, in parallel
  - PROFILE=testing

install:
  # Create setup.php
  - ln -s .travis.setup.php setup.php
  - composer update
  # Install the testing profile
  - tests/database_setup.sh "$PROFILE"

before_script:
  # Go into the tests directory to run the tests
  - cd tests/

branches:
  only:
    - develop
    - master
    - master-fix
    - wip/playground
